version: 0.0
os: linux
files:
    - source: target/webportal.war
      destination: /tmp/codedeploy-deployment-staging-area
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timemout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timout: 300
      runas: root
