version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
