version: 0.0
os: linux
files:
  - source: /target/AIMAcademyCMS.war
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
 ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
 ValidateService:
    - locaiton: scripts/basic_health_check.sh
